spring:
  application:
    name: yu-ai-agent
  profiles:
    active: local
  # 文件上传配置
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB
# 临时注释掉，便于大家开发调试和部署（实际填写 PgVector 数据库信息）
    datasource:
       url:
        jdbc:postgresql://localhost:5432/yu_ai_agent
       username: postgres
       password: 020324
  ai:
    dashscope:
      # 需要替换为你自己的 key
      api-key: sk-ws-H.EIXXEYD.4LG7.MEQCIBC-UmJ5Yh9ZgFxi_peve3q0s89iBeJ7y5yVU1w23PH6AiAy94BQez69TonaZR1s8OJUUCU1KKtmpcxTOuIcoJQRkQ
      chat:
        options:
          model: qwen-plus
    ollama:
      base-url: http://localhost:11434
      chat:
        model: gemma3:1b
# 临时注释掉，便于大家开发调试和部署（实际需要启动 MCP 服务）
#    mcp:
#      client:
#        sse:
#          connections:
#            server1:
#              url: http://localhost:8127
#        stdio:
#          servers-configuration: classpath:mcp-servers.json
# 临时注释掉，便于大家开发调试和部署（实际需要启动 PgVector 数据库）
      vectorstore:
        pgvector:
          index-type: HNSW
          dimensions: 1536
          distance-type: COSINE_DISTANCE
          max-document-batch-size: 10000 # Optional: Maximum number of documents per batch
server:
  port: 8123
  servlet:
    context-path: /api

# 会话保存配置（使用绝对路径，避免相对路径导致的位置混乱）
app:
  session:
    save-dir: C:/Users/27662/yu-ai-agent/sessions
# springdoc-openapi config
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.zhangbo.yuaiagent.controller
# knife4j config
knife4j:
  enable: true
  setting:
    language: zh_cn
# searchAPI
search-api:
  # 需要替换为你自己的 key
  api-key: dpnLRxAUPqEak3vfkHDwSWed
# 修改日志级别，查看 Spring AI 更多调用细节
logging:
  level:
    org.springframework.ai: DEBUG